//
// Created by Roumite on 14/03/2026.
//

#pragma once

#include <map>
#include <array>
#include <string_view>

namespace compiler
{
    enum LexerTokensTypes
    {
        TOKEN_KEYWORD_FUNCTION,
        TOKEN_KEYWORD_IF,
        TOKEN_KEYWORD_ELSE,
        TOKEN_KEYWORD_WHILE,
        TOKEN_KEYWORD_RETURN,
        TOKEN_KEYWORD_FOR,
        TOKEN_KEYWORD_EXPORT,
        TOKEN_KEYWORD_BREAK,
        TOKEN_KEYWORD_CONTINUE,

        TOKEN_TYPE_UINT8,
        TOKEN_TYPE_INT8,
        TOKEN_TYPE_UINT16,
        TOKEN_TYPE_INT16,
        TOKEN_TYPE_UINT32,
        TOKEN_TYPE_INT32,
        TOKEN_TYPE_BOOL,
        TOKEN_TYPE_VOID,

        TOKEN_BOOL_TRUE,
        TOKEN_BOOL_FALSE,

        TOKEN_OPERATOR_PLUS,
        TOKEN_OPERATOR_MINUS,
        TOKEN_OPERATOR_MULTIPLY,
        TOKEN_OPERATOR_DIVIDE,
        TOKEN_OPERATOR_MODULUS,
        TOKEN_OPERATOR_NOT,
        TOKEN_OPERATOR_REFERENCE,
        TOKEN_OPERATOR_DEREFERENCE,

        TOKEN_COMPARISON_EQUAL,
        TOKEN_COMPARISON_NOT_EQUAL,
        TOKEN_COMPARISON_LESS,
        TOKEN_COMPARISON_GREATER,
        TOKEN_COMPARISON_LESS_OR_EQUAL,
        TOKEN_COMPARISON_GREATER_OR_EQUAL,
        TOKEN_COMPARISON_AND,
        TOKEN_COMPARISON_OR,

        TOKEN_PUNCTUATION_LEFT_PARENTHESIS,
        TOKEN_PUNCTUATION_RIGHT_PARENTHESIS,
        TOKEN_PUNCTUATION_LEFT_BRACKET,
        TOKEN_PUNCTUATION_RIGHT_BRACKET,
        TOKEN_PUNCTUATION_LEFT_SQUARE_BRACKET,
        TOKEN_PUNCTUATION_RIGHT_SQUARE_BRACKET,
        TOKEN_PUNCTUATION_COMMA,
        TOKEN_PUNCTUATION_SEMICOLON,
        TOKEN_PUNCTUATION_ARROW,

        TOKEN_ASSIGNMENT,

        TOKEN_INTEGER,
        TOKEN_IDENTIFIER, // Variable identifier, for example
        TOKEN_STRING,
        TOKEN_EOF // Automatically added by lexer at the end of the file
    };

    struct TokenEntry {
        std::string_view name;
        LexerTokensTypes type;
    };

    constexpr std::array KEYWORDS = {
        // Keywords
        TokenEntry{"fn", TOKEN_KEYWORD_FUNCTION},
        TokenEntry{"if", TOKEN_KEYWORD_IF},
        TokenEntry{"else", TOKEN_KEYWORD_ELSE},
        TokenEntry{"while", TOKEN_KEYWORD_WHILE},
        TokenEntry{"return", TOKEN_KEYWORD_RETURN},
        TokenEntry{"for", TOKEN_KEYWORD_FOR},
        TokenEntry{"export", TOKEN_KEYWORD_EXPORT},
        TokenEntry{"break", TOKEN_KEYWORD_BREAK},
        TokenEntry{"continue", TOKEN_KEYWORD_CONTINUE},

        // Types
        TokenEntry{"uint8", TOKEN_TYPE_UINT8},
        TokenEntry{"int8", TOKEN_TYPE_INT8},
        TokenEntry{"uint16", TOKEN_TYPE_UINT16},
        TokenEntry{"int16", TOKEN_TYPE_INT16},
        TokenEntry{"uint32", TOKEN_TYPE_UINT32},
        TokenEntry{"int32", TOKEN_TYPE_INT32},
        TokenEntry{"bool", TOKEN_TYPE_BOOL},
        TokenEntry{"void", TOKEN_TYPE_VOID},

        // Literals
        TokenEntry{"true", TOKEN_BOOL_TRUE},
        TokenEntry{"false", TOKEN_BOOL_FALSE},

        // Assigment
        TokenEntry{"=", TOKEN_ASSIGNMENT},

        // Operator
        TokenEntry{"+", TOKEN_OPERATOR_PLUS},
        TokenEntry{"-", TOKEN_OPERATOR_MINUS},
        TokenEntry{"*", TOKEN_OPERATOR_MULTIPLY},
        TokenEntry{"/", TOKEN_OPERATOR_DIVIDE},
        TokenEntry{"%", TOKEN_OPERATOR_MODULUS},
        TokenEntry{"!", TOKEN_OPERATOR_NOT},
        TokenEntry{"&", TOKEN_OPERATOR_REFERENCE},
        TokenEntry{"#", TOKEN_OPERATOR_DEREFERENCE},

        // Comparison
        TokenEntry{"==", TOKEN_COMPARISON_EQUAL},
        TokenEntry{"!=", TOKEN_COMPARISON_NOT_EQUAL},
        TokenEntry{"<", TOKEN_COMPARISON_LESS},
        TokenEntry{">", TOKEN_COMPARISON_GREATER},
        TokenEntry{"<=", TOKEN_COMPARISON_LESS_OR_EQUAL},
        TokenEntry{">=", TOKEN_COMPARISON_GREATER_OR_EQUAL},
        TokenEntry{"&&", TOKEN_COMPARISON_AND},
        TokenEntry{"||", TOKEN_COMPARISON_OR},

        // Punctuation
        TokenEntry{"(", TOKEN_PUNCTUATION_LEFT_PARENTHESIS},
        TokenEntry{")", TOKEN_PUNCTUATION_RIGHT_PARENTHESIS},
        TokenEntry{"{", TOKEN_PUNCTUATION_LEFT_BRACKET},
        TokenEntry{"}", TOKEN_PUNCTUATION_RIGHT_BRACKET},
        TokenEntry{"[", TOKEN_PUNCTUATION_LEFT_SQUARE_BRACKET},
        TokenEntry{"]", TOKEN_PUNCTUATION_RIGHT_SQUARE_BRACKET},
        TokenEntry{",", TOKEN_PUNCTUATION_COMMA},
        TokenEntry{";", TOKEN_PUNCTUATION_SEMICOLON},
        TokenEntry{"->", TOKEN_PUNCTUATION_ARROW},
    };

    inline std::map<LexerTokensTypes, std::string_view> token_type_to_string = {
        {TOKEN_KEYWORD_FUNCTION, "TOKEN_KEYWORD_FUNCTION"},
        {TOKEN_KEYWORD_IF, "TOKEN_KEYWORD_IF"},
        {TOKEN_KEYWORD_WHILE, "TOKEN_KEYWORD_WHILE"},
        {TOKEN_KEYWORD_RETURN, "TOKEN_KEYWORD_RETURN"},
        {TOKEN_KEYWORD_FOR, "TOKEN_KEYWORD_FOR"},
        {TOKEN_KEYWORD_EXPORT, "TOKEN_KEYWORD_EXPORT"},
        {TOKEN_TYPE_UINT8, "TOKEN_TYPE_UINT8"},
        {TOKEN_TYPE_INT8, "TOKEN_TYPE_INT8"},
        {TOKEN_TYPE_UINT16, "TOKEN_TYPE_UINT16"},
        {TOKEN_TYPE_INT16, "TOKEN_TYPE_INT16"},
        {TOKEN_TYPE_UINT32, "TOKEN_TYPE_UINT32"},
        {TOKEN_TYPE_INT32, "TOKEN_TYPE_INT32"},
        {TOKEN_TYPE_BOOL, "TOKEN_TYPE_BOOL"},
        {TOKEN_TYPE_VOID, "TOKEN_TYPE_VOID"},
        {TOKEN_BOOL_TRUE, "TOKEN_BOOL_TRUE"},
        {TOKEN_BOOL_FALSE, "TOKEN_BOOL_FALSE"},
        {TOKEN_OPERATOR_PLUS, "TOKEN_OPERATOR_PLUS"},
        {TOKEN_OPERATOR_MINUS, "TOKEN_OPERATOR_MINUS"},
        {TOKEN_OPERATOR_MULTIPLY, "TOKEN_OPERATOR_MULTIPLY"},
        {TOKEN_OPERATOR_DIVIDE, "TOKEN_OPERATOR_DIVIDE"},
        {TOKEN_OPERATOR_MODULUS, "TOKEN_OPERATOR_MODULUS"},
        {TOKEN_OPERATOR_NOT, "TOKEN_OPERATOR_NOT"},
        {TOKEN_OPERATOR_REFERENCE, "TOKEN_OPERATOR_REFERENCE"},
        {TOKEN_OPERATOR_DEREFERENCE, "TOKEN_OPERATOR_DEREFERENCE"},
        {TOKEN_COMPARISON_EQUAL, "TOKEN_COMPARISON_EQUAL"},
        {TOKEN_COMPARISON_NOT_EQUAL, "TOKEN_COMPARISON_NOT_EQUAL"},
        {TOKEN_COMPARISON_LESS, "TOKEN_COMPARISON_LESS"},
        {TOKEN_COMPARISON_GREATER, "TOKEN_COMPARISON_GREATER"},
        {TOKEN_COMPARISON_LESS_OR_EQUAL, "TOKEN_COMPARISON_LESS_OR_EQUAL"},
        {TOKEN_COMPARISON_GREATER_OR_EQUAL, "TOKEN_COMPARISON_GREATER_OR_EQUAL"},
        {TOKEN_COMPARISON_AND, "TOKEN_COMPARISON_AND"},
        {TOKEN_COMPARISON_OR, "TOKEN_COMPARISON_OR"},
        {TOKEN_PUNCTUATION_LEFT_PARENTHESIS, "TOKEN_PUNCTUATION_LEFT_PARENTHESIS"},
        {TOKEN_PUNCTUATION_RIGHT_PARENTHESIS, "TOKEN_PUNCTUATION_RIGHT_PARENTHESIS"},
        {TOKEN_PUNCTUATION_LEFT_BRACKET, "TOKEN_PUNCTUATION_LEFT_BRACKET"},
        {TOKEN_PUNCTUATION_RIGHT_BRACKET, "TOKEN_PUNCTUATION_RIGHT_BRACKET"},
        {TOKEN_PUNCTUATION_LEFT_SQUARE_BRACKET, "TOKEN_PUNCTUATION_LEFT_SQUARE_BRACKET"},
        {TOKEN_PUNCTUATION_RIGHT_SQUARE_BRACKET, "TOKEN_PUNCTUATION_RIGHT_SQUARE_BRACKET"},
        {TOKEN_PUNCTUATION_COMMA, "TOKEN_PUNCTUATION_COMMA"},
        {TOKEN_PUNCTUATION_SEMICOLON, "TOKEN_PUNCTUATION_SEMICOLON"},
        {TOKEN_PUNCTUATION_ARROW, "TOKEN_PUNCTUATION_ARROW"},
        {TOKEN_ASSIGNMENT, "TOKEN_ASSIGNMENT"},
        {TOKEN_INTEGER, "TOKEN_INTEGER"},
        {TOKEN_IDENTIFIER, "TOKEN_IDENTIFIER"},
        {TOKEN_STRING, "TOKEN_STRING"},
        {TOKEN_EOF, "TOKEN_EOF"}
    };
}