//
// Created by Roumite on 14/03/2026.
//

#pragma once

#include <map>
#include <array>
#include <string_view>

namespace compiler
{
    enum LexerTokenCategory
    {
        TOKEN_CATH_KEYWORD,
        TOKEN_CATH_TYPE,
        TOKEN_CATH_OPERATOR,
        TOKEN_CATH_NUMBER,
        TOKEN_CATH_STRING,
        TOKEN_CATH_CONSTANT,
        TOKEN_CATH_NO_CATH, // Then no coloration

        TOKEN_CATH_FUNCTION,
        TOKEN_CATH_FUNCTION_CALL,
        TOKEN_CATH_VARIABLE,
        TOKEN_CATH_PARAMETER
    };

    enum LexerTokenType
    {
        TOKEN_KEYWORD_FUNCTION,
        TOKEN_KEYWORD_IF,
        TOKEN_KEYWORD_ELSE,
        TOKEN_KEYWORD_WHILE,
        TOKEN_KEYWORD_RETURN,
        TOKEN_KEYWORD_FOR,
        TOKEN_KEYWORD_EXPORT,
        TOKEN_KEYWORD_BREAK,
        TOKEN_KEYWORD_CONTINUE,
        TOKEN_KEYWORD_IMPORT,
        TOKEN_KEYWORD_FROM,
        TOKEN_KEYWORD_FILES,

        TOKEN_TYPE_UINT8,
        TOKEN_TYPE_UINT16,
        TOKEN_TYPE_UINT32,
        TOKEN_TYPE_INT,
        TOKEN_TYPE_FLOAT,
        TOKEN_TYPE_BOOL,
        TOKEN_TYPE_VOID,
        TOKEN_TYPE_FILE,
        TOKEN_TYPE_CLOCK,
        TOKEN_TYPE_FRAMEBUFFER,

        TOKEN_BOOL_TRUE,
        TOKEN_BOOL_FALSE,

        TOKEN_OPERATOR_PLUS,
        TOKEN_OPERATOR_MINUS,
        TOKEN_OPERATOR_MULTIPLY,
        TOKEN_OPERATOR_DIVIDE,
        TOKEN_OPERATOR_MODULUS,
        TOKEN_OPERATOR_NOT,
        TOKEN_OPERATOR_REFERENCE,
        TOKEN_OPERATOR_DEREFERENCE,

        TOKEN_COMPARISON_EQUAL,
        TOKEN_COMPARISON_NOT_EQUAL,
        TOKEN_COMPARISON_LESS,
        TOKEN_COMPARISON_GREATER,
        TOKEN_COMPARISON_LESS_OR_EQUAL,
        TOKEN_COMPARISON_GREATER_OR_EQUAL,
        TOKEN_COMPARISON_AND,
        TOKEN_COMPARISON_OR,

        TOKEN_PUNCTUATION_LEFT_PARENTHESIS,
        TOKEN_PUNCTUATION_RIGHT_PARENTHESIS,
        TOKEN_PUNCTUATION_LEFT_BRACKET,
        TOKEN_PUNCTUATION_RIGHT_BRACKET,
        TOKEN_PUNCTUATION_LEFT_SQUARE_BRACKET,
        TOKEN_PUNCTUATION_RIGHT_SQUARE_BRACKET,
        TOKEN_PUNCTUATION_COMMA,
        TOKEN_PUNCTUATION_SEMICOLON,
        TOKEN_PUNCTUATION_COLON,
        TOKEN_PUNCTUATION_ARROW,

        TOKEN_ASSIGNMENT,
        TOKEN_ADD_ASSIGNMENT,
        TOKEN_SUB_ASSIGNMENT,
        TOKEN_MUL_ASSIGNMENT,
        TOKEN_DIV_ASSIGNMENT,

        TOKEN_INTEGER,
        TOKEN_FLOAT,
        TOKEN_IDENTIFIER, // Variable identifier, for example
        TOKEN_STRING,
        TOKEN_BOF, // Automatically added by lexer at the beginning of the file
        TOKEN_EOF, // Automatically added by lexer at the end of the file

        TOKEN_NO_TYPE // Automatically added by lexer at the end of the file
    };

    struct TokenEntry {
        std::string_view name;
        LexerTokenType type;
    };


    constexpr std::array KEYWORDS = {
        // Keywords
        TokenEntry{"fn", TOKEN_KEYWORD_FUNCTION},
        TokenEntry{"if", TOKEN_KEYWORD_IF},
        TokenEntry{"else", TOKEN_KEYWORD_ELSE},
        TokenEntry{"while", TOKEN_KEYWORD_WHILE},
        TokenEntry{"return", TOKEN_KEYWORD_RETURN},
        TokenEntry{"for", TOKEN_KEYWORD_FOR},
        TokenEntry{"export", TOKEN_KEYWORD_EXPORT},
        TokenEntry{"break", TOKEN_KEYWORD_BREAK},
        TokenEntry{"continue", TOKEN_KEYWORD_CONTINUE},
        TokenEntry{"import", TOKEN_KEYWORD_IMPORT},
        TokenEntry{"from", TOKEN_KEYWORD_FROM},
        TokenEntry{"files", TOKEN_KEYWORD_FILES},

        // Types
        TokenEntry{"uint8", TOKEN_TYPE_UINT8},
        TokenEntry{"uint16", TOKEN_TYPE_UINT16},
        TokenEntry{"uint32", TOKEN_TYPE_UINT32},
        TokenEntry{"int", TOKEN_TYPE_INT},
        TokenEntry{"float", TOKEN_TYPE_FLOAT},
        TokenEntry{"bool", TOKEN_TYPE_BOOL},
        TokenEntry{"void", TOKEN_TYPE_VOID},
        TokenEntry{"file", TOKEN_TYPE_FILE},
        TokenEntry{"clock", TOKEN_TYPE_CLOCK},
        TokenEntry{"framebuffer", TOKEN_TYPE_FRAMEBUFFER},

        // Literals
        TokenEntry{"true", TOKEN_BOOL_TRUE},
        TokenEntry{"false", TOKEN_BOOL_FALSE},

        // Assigment
        TokenEntry{"=", TOKEN_ASSIGNMENT},
        TokenEntry{"+=", TOKEN_ADD_ASSIGNMENT},
        TokenEntry{"-=", TOKEN_SUB_ASSIGNMENT},
        TokenEntry{"*=", TOKEN_MUL_ASSIGNMENT},
        TokenEntry{"/=", TOKEN_DIV_ASSIGNMENT},

        // Operator
        TokenEntry{"+", TOKEN_OPERATOR_PLUS},
        TokenEntry{"-", TOKEN_OPERATOR_MINUS},
        TokenEntry{"*", TOKEN_OPERATOR_MULTIPLY},
        TokenEntry{"/", TOKEN_OPERATOR_DIVIDE},
        TokenEntry{"%", TOKEN_OPERATOR_MODULUS},
        TokenEntry{"!", TOKEN_OPERATOR_NOT},
        TokenEntry{"@", TOKEN_OPERATOR_REFERENCE},
        TokenEntry{"#", TOKEN_OPERATOR_DEREFERENCE},

        // Comparison
        TokenEntry{"==", TOKEN_COMPARISON_EQUAL},
        TokenEntry{"!=", TOKEN_COMPARISON_NOT_EQUAL},
        TokenEntry{"<", TOKEN_COMPARISON_LESS},
        TokenEntry{">", TOKEN_COMPARISON_GREATER},
        TokenEntry{"<=", TOKEN_COMPARISON_LESS_OR_EQUAL},
        TokenEntry{">=", TOKEN_COMPARISON_GREATER_OR_EQUAL},
        TokenEntry{"&&", TOKEN_COMPARISON_AND},
        TokenEntry{"||", TOKEN_COMPARISON_OR},

        // Punctuation
        TokenEntry{"(", TOKEN_PUNCTUATION_LEFT_PARENTHESIS},
        TokenEntry{")", TOKEN_PUNCTUATION_RIGHT_PARENTHESIS},
        TokenEntry{"{", TOKEN_PUNCTUATION_LEFT_BRACKET},
        TokenEntry{"}", TOKEN_PUNCTUATION_RIGHT_BRACKET},
        TokenEntry{"[", TOKEN_PUNCTUATION_LEFT_SQUARE_BRACKET},
        TokenEntry{"]", TOKEN_PUNCTUATION_RIGHT_SQUARE_BRACKET},
        TokenEntry{",", TOKEN_PUNCTUATION_COMMA},
        TokenEntry{";", TOKEN_PUNCTUATION_SEMICOLON},
        TokenEntry{":", TOKEN_PUNCTUATION_COLON},
        TokenEntry{"->", TOKEN_PUNCTUATION_ARROW},
    };
    inline std::map<LexerTokenType, std::string_view> token_type_to_string = {
        {TOKEN_KEYWORD_FUNCTION, "TOKEN_KEYWORD_FUNCTION"},
        {TOKEN_KEYWORD_IF, "TOKEN_KEYWORD_IF"},
        {TOKEN_KEYWORD_ELSE, "TOKEN_KEYWORD_ELSE"},
        {TOKEN_KEYWORD_WHILE, "TOKEN_KEYWORD_WHILE"},
        {TOKEN_KEYWORD_RETURN, "TOKEN_KEYWORD_RETURN"},
        {TOKEN_KEYWORD_FOR, "TOKEN_KEYWORD_FOR"},
        {TOKEN_KEYWORD_EXPORT, "TOKEN_KEYWORD_EXPORT"},
        {TOKEN_KEYWORD_BREAK, "TOKEN_KEYWORD_BREAK"},
        {TOKEN_KEYWORD_CONTINUE, "TOKEN_KEYWORD_CONTINUE"},
        {TOKEN_KEYWORD_IMPORT, "TOKEN_KEYWORD_IMPORT"},
        {TOKEN_KEYWORD_FROM, "TOKEN_KEYWORD_FROM"},
        {TOKEN_KEYWORD_FILES, "TOKEN_KEYWORD_FILES"},
        {TOKEN_TYPE_UINT8, "TOKEN_TYPE_UINT8"},
        {TOKEN_TYPE_UINT16, "TOKEN_TYPE_UINT16"},
        {TOKEN_TYPE_UINT32, "TOKEN_TYPE_UINT32"},
        {TOKEN_TYPE_INT, "TOKEN_TYPE_INT"},
        {TOKEN_TYPE_FLOAT, "TOKEN_TYPE_FLOAT"},
        {TOKEN_TYPE_BOOL, "TOKEN_TYPE_BOOL"},
        {TOKEN_TYPE_VOID, "TOKEN_TYPE_VOID"},
        {TOKEN_TYPE_FRAMEBUFFER, "TOKEN_TYPE_FRAMEBUFFER"},
        {TOKEN_BOOL_TRUE, "TOKEN_BOOL_TRUE"},
        {TOKEN_BOOL_FALSE, "TOKEN_BOOL_FALSE"},
        {TOKEN_OPERATOR_PLUS, "TOKEN_OPERATOR_PLUS"},
        {TOKEN_OPERATOR_MINUS, "TOKEN_OPERATOR_MINUS"},
        {TOKEN_OPERATOR_MULTIPLY, "TOKEN_OPERATOR_MULTIPLY"},
        {TOKEN_OPERATOR_DIVIDE, "TOKEN_OPERATOR_DIVIDE"},
        {TOKEN_OPERATOR_MODULUS, "TOKEN_OPERATOR_MODULUS"},
        {TOKEN_OPERATOR_NOT, "TOKEN_OPERATOR_NOT"},
        {TOKEN_OPERATOR_REFERENCE, "TOKEN_OPERATOR_REFERENCE"},
        {TOKEN_OPERATOR_DEREFERENCE, "TOKEN_OPERATOR_DEREFERENCE"},
        {TOKEN_COMPARISON_EQUAL, "TOKEN_COMPARISON_EQUAL"},
        {TOKEN_COMPARISON_NOT_EQUAL, "TOKEN_COMPARISON_NOT_EQUAL"},
        {TOKEN_COMPARISON_LESS, "TOKEN_COMPARISON_LESS"},
        {TOKEN_COMPARISON_GREATER, "TOKEN_COMPARISON_GREATER"},
        {TOKEN_COMPARISON_LESS_OR_EQUAL, "TOKEN_COMPARISON_LESS_OR_EQUAL"},
        {TOKEN_COMPARISON_GREATER_OR_EQUAL, "TOKEN_COMPARISON_GREATER_OR_EQUAL"},
        {TOKEN_COMPARISON_AND, "TOKEN_COMPARISON_AND"},
        {TOKEN_COMPARISON_OR, "TOKEN_COMPARISON_OR"},
        {TOKEN_PUNCTUATION_LEFT_PARENTHESIS, "TOKEN_PUNCTUATION_LEFT_PARENTHESIS"},
        {TOKEN_PUNCTUATION_RIGHT_PARENTHESIS, "TOKEN_PUNCTUATION_RIGHT_PARENTHESIS"},
        {TOKEN_PUNCTUATION_LEFT_BRACKET, "TOKEN_PUNCTUATION_LEFT_BRACKET"},
        {TOKEN_PUNCTUATION_RIGHT_BRACKET, "TOKEN_PUNCTUATION_RIGHT_BRACKET"},
        {TOKEN_PUNCTUATION_LEFT_SQUARE_BRACKET, "TOKEN_PUNCTUATION_LEFT_SQUARE_BRACKET"},
        {TOKEN_PUNCTUATION_RIGHT_SQUARE_BRACKET, "TOKEN_PUNCTUATION_RIGHT_SQUARE_BRACKET"},
        {TOKEN_PUNCTUATION_COMMA, "TOKEN_PUNCTUATION_COMMA"},
        {TOKEN_PUNCTUATION_SEMICOLON, "TOKEN_PUNCTUATION_SEMICOLON"},
        {TOKEN_PUNCTUATION_COLON, "TOKEN_PUNCTUATION_COLON"},
        {TOKEN_PUNCTUATION_ARROW, "TOKEN_PUNCTUATION_ARROW"},
        {TOKEN_ASSIGNMENT, "TOKEN_ASSIGNMENT"},
        {TOKEN_ADD_ASSIGNMENT, "TOKEN_ADD_ASSIGNMENT"},
        {TOKEN_SUB_ASSIGNMENT, "TOKEN_SUB_ASSIGNMENT"},
        {TOKEN_MUL_ASSIGNMENT, "TOKEN_MUL_ASSIGNMENT"},
        {TOKEN_DIV_ASSIGNMENT, "TOKEN_DIV_ASSIGNMENT"},
        {TOKEN_INTEGER, "TOKEN_INTEGER"},
        {TOKEN_FLOAT, "TOKEN_FLOAT"},
        {TOKEN_IDENTIFIER, "TOKEN_IDENTIFIER"},
        {TOKEN_STRING, "TOKEN_STRING"},
        {TOKEN_BOF, "TOKEN_BOF"},
        {TOKEN_EOF, "TOKEN_EOF"},
        {TOKEN_NO_TYPE, "TOKEN_NO_TYPE"},
        {TOKEN_TYPE_FILE, "TOKEN_TYPE_FILE"},
        {TOKEN_TYPE_CLOCK, "TOKEN_TYPE_CLOCK"}
    };

    inline std::map<LexerTokenType, LexerTokenCategory> token_type_to_category = {
    {TOKEN_KEYWORD_FUNCTION, TOKEN_CATH_KEYWORD},
    {TOKEN_KEYWORD_IF, TOKEN_CATH_KEYWORD},
    {TOKEN_KEYWORD_ELSE, TOKEN_CATH_KEYWORD},
    {TOKEN_KEYWORD_WHILE, TOKEN_CATH_KEYWORD},
    {TOKEN_KEYWORD_RETURN, TOKEN_CATH_KEYWORD},
    {TOKEN_KEYWORD_FOR, TOKEN_CATH_KEYWORD},
    {TOKEN_KEYWORD_EXPORT, TOKEN_CATH_KEYWORD},
    {TOKEN_KEYWORD_BREAK, TOKEN_CATH_KEYWORD},
    {TOKEN_KEYWORD_CONTINUE, TOKEN_CATH_KEYWORD},
    {TOKEN_KEYWORD_IMPORT, TOKEN_CATH_KEYWORD},
    {TOKEN_KEYWORD_FROM, TOKEN_CATH_KEYWORD},
    {TOKEN_KEYWORD_FILES, TOKEN_CATH_KEYWORD},

    {TOKEN_TYPE_UINT8, TOKEN_CATH_TYPE},
    {TOKEN_TYPE_UINT16, TOKEN_CATH_TYPE},
    {TOKEN_TYPE_UINT32, TOKEN_CATH_TYPE},
    {TOKEN_TYPE_INT, TOKEN_CATH_TYPE},
    {TOKEN_TYPE_BOOL, TOKEN_CATH_TYPE},
    {TOKEN_TYPE_VOID, TOKEN_CATH_TYPE},
    {TOKEN_TYPE_FILE, TOKEN_CATH_TYPE},
    {TOKEN_TYPE_CLOCK, TOKEN_CATH_TYPE},
    {TOKEN_TYPE_FRAMEBUFFER, TOKEN_CATH_TYPE},

    {TOKEN_OPERATOR_PLUS, TOKEN_CATH_OPERATOR},
    {TOKEN_OPERATOR_MINUS, TOKEN_CATH_OPERATOR},
    {TOKEN_OPERATOR_MULTIPLY, TOKEN_CATH_OPERATOR},
    {TOKEN_OPERATOR_DIVIDE, TOKEN_CATH_OPERATOR},
    {TOKEN_OPERATOR_MODULUS, TOKEN_CATH_OPERATOR},
    {TOKEN_OPERATOR_NOT, TOKEN_CATH_OPERATOR},
    {TOKEN_OPERATOR_REFERENCE, TOKEN_CATH_OPERATOR},
    {TOKEN_OPERATOR_DEREFERENCE, TOKEN_CATH_OPERATOR},
    {TOKEN_COMPARISON_EQUAL, TOKEN_CATH_OPERATOR},
    {TOKEN_COMPARISON_NOT_EQUAL, TOKEN_CATH_OPERATOR},
    {TOKEN_COMPARISON_LESS, TOKEN_CATH_OPERATOR},
    {TOKEN_COMPARISON_GREATER, TOKEN_CATH_OPERATOR},
    {TOKEN_COMPARISON_LESS_OR_EQUAL, TOKEN_CATH_OPERATOR},
    {TOKEN_COMPARISON_GREATER_OR_EQUAL, TOKEN_CATH_OPERATOR},
    {TOKEN_COMPARISON_AND, TOKEN_CATH_OPERATOR},
    {TOKEN_COMPARISON_OR, TOKEN_CATH_OPERATOR},
    {TOKEN_ASSIGNMENT, TOKEN_CATH_OPERATOR},
    {TOKEN_ADD_ASSIGNMENT, TOKEN_CATH_OPERATOR},
    {TOKEN_SUB_ASSIGNMENT, TOKEN_CATH_OPERATOR},
    {TOKEN_MUL_ASSIGNMENT, TOKEN_CATH_OPERATOR},
    {TOKEN_DIV_ASSIGNMENT, TOKEN_CATH_OPERATOR},
    {TOKEN_PUNCTUATION_ARROW, TOKEN_CATH_OPERATOR},

    {TOKEN_BOOL_TRUE, TOKEN_CATH_KEYWORD},
    {TOKEN_BOOL_FALSE, TOKEN_CATH_KEYWORD},
    {TOKEN_INTEGER, TOKEN_CATH_NUMBER},
    {TOKEN_FLOAT, TOKEN_CATH_NUMBER},
    {TOKEN_STRING, TOKEN_CATH_STRING}
};
}